### PR TITLE
🍾 Updated contributorsList.js

### PR DESCRIPTION
**Pull request by LionessLilo**

### CODE REVIEW

**Comment by LionessLilo** [comment]
@LionessLilo Please Star ⭐️ the repo to earn '**_hacktober-accepted_**' label for the event.

**Comment by GauravSahu891** [comment]
hey @LionessLilo how did you merge this file would anybody is assign this issue to you or you work on this issue by yourself.
because github is talking about write access and also I worked on code_of_conduct so should I directly fix the issue on github or i folk it and make another branch.
please REPLY.

**Comment by LionessLilo** [comment]
@GauravSahu891 according to the instructions on the repo's page, you need to fork the repo. I then did the changes on Github, pushed my changes and did a pull request.

**Comment by GauravSahu891** [comment]
@LionessLilo is your PR get merged?

**Comment by LionessLilo** [comment]
@GauravSahu891 No mine has not been merged yet, I think they going to do them all at once later on.

**Pull request closed without merging**
